# This is a basic workflow to help you get started with Actions

name: azure bicep deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: 'bicep build'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      # Run az deployment command with bicep template
      - name: az bicep deploy
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
          az deployment group create --what-if --resource-group bicep-deploy-rg --template-file ./storage_account.bicep --parameters @parameters.json
          
          
  deploy:
    name: 'bicep deploy'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build]
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      # Run az deployment command with bicep template
      - name: az bicep deploy
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
          az deployment group create --resource-group bicep-deploy-rg --template-file ./storage_account.bicep --parameters @parameters.json
